In [1]:
import numpy as np
import pylab as pl

In [28]:
def normalize(feature): 
    minimum = np.min(feature)
    maximum = np.max(feature)
    range = maximum - minimum
    feature_norm = (feature - minimum)/range
    return feature_norm.tolist()

In [5]:
data = pl.genfromtxt("all_data.txt", names = True)

In [9]:
#Rigidities of particles (R = E/Z, measured in volts)

R = data['rigidity']
print("Minimum rigidity = {} V, maximum rigidity = {} V".format(np.min(R), np.max(R)))

Minimum rigidity = 7.47948962893499e+17 V, maximum rigidity = 2.884031503126612e+20 V


In [12]:
#Unit vectors of incoming particle momenta; these give the direction that the cosmic ray was detected from

px, py, pz = data['px'], data['py'], data['pz']
print(px)

[0.54903915 0.66518648 0.60511293 ... 0.67832474 0.57621362 0.03035867]


In [13]:
#For each pixel, particle rigidity, and source combination: 
#the normalized fraction of that particle rigidity arriving in that pixel 

N = data['Nparticles']
print(N)

[3.65188565e-04 1.01782102e-03 1.05754305e-46 ... 6.23778231e-06
 7.78522069e-05 8.11476543e-88]


In [18]:
#Source coordinates of whatever produced the cosmic ray

x0, y0, z0 = data["x0"], data["y0"], data["z0"]

sourceCoords = np.stack((x0, y0, z0), axis = 1)
print(sourceCoords)

[[-3.34  1.25 -3.56]
 [-3.34  1.25 -3.56]
 [ 2.76 -3.15 -2.86]
 ...
 [ 2.76 -3.15 -2.86]
 [ 2.76 -3.15 -2.86]
 [-3.34  1.25 -3.56]]


In [26]:
features = np.stack((R, px, py, pz, N), axis = 1)
print(features)

[[ 4.34450207e+18  5.49039155e-01 -2.53110517e-01 -7.96549479e-01
   3.65188565e-04]
 [ 3.61359943e+18  6.65186475e-01 -1.52507423e-01 -7.30936686e-01
   1.01782102e-03]
 [ 8.31763771e+19  6.05112935e-01 -6.27810876e-01  4.89583333e-01
   1.05754305e-46]
 ...
 [ 7.54987930e+18  6.78324744e-01 -6.37929883e-01  3.64583333e-01
   6.23778231e-06]
 [ 5.46940406e+18  5.76213620e-01 -7.57330638e-01  3.07291667e-01
   7.78522069e-05]
 [ 1.58489319e+20  3.03586720e-02  2.32950283e-02 -9.99267578e-01
   8.11476543e-88]]


In [31]:
np.shape(features)

(1352, 5)

In [29]:
for i in range(np.shape(features)[1]): 
    feature = features[:, i]
    feature_norm = normalize(feature)
    features[:, i] = feature_norm

In [30]:
print(features)

[[1.25030004e-02 5.99841184e-01 4.65870065e-01 1.31864796e-01
  9.73774411e-03]
 [9.96210203e-03 7.22636860e-01 5.29007507e-01 1.74429501e-01
  2.71401726e-02]
 [2.86552886e-01 6.59124668e-01 2.30712068e-01 9.66212203e-01
  2.81993595e-45]
 ...
 [2.36461232e-02 7.36527172e-01 2.24361486e-01 8.85121491e-01
  1.66330312e-04]
 [1.64135919e-02 6.28571135e-01 1.49426829e-01 8.47954914e-01
  2.07592719e-03]
 [5.48369609e-01 5.14710605e-02 6.39339273e-01 3.56355669e-04
  1.87687846e-86]]
